### ISSUE TITLE
Omit element if value and attribute null/undefined

### ISSUE THREAD

**Issue by brecode** [chilts/data2xml#14]
Hi, 

Is there a way to omit an element if the attribute is set to null or undefined. 
I am playing with libvirt and a way to define networks is this:  
```xml
...
 <forward mode='nat'>
    <nat>
      <address start='1.2.3.4' end='1.2.3.10'/>
    </nat>
  </forward>
...
```
I was wondering if there are no 'start' or 'end' values (null or undefined) is it possible to delete the address and obviously the nat elements
Thank you. 
@chilts

**Comment by chilts** [comment]
There's no way to do that at the moment. You'd essentially get an empty `<address>` tag. Currently data2xml is pretty simple and I'd be afraid that this would add a lot of complexity (ie. running up the tree making sure each element has something defined, whether it is an attribute or another element). Ah ... I guess running up also means checking sibling nodes along the way too!!!

This could get nasty.

I'm gonna close this as won't fix since I think data2xml shouldn't do this. Instead, I'd suggest that you know your data best and if you have an empty start and end, then you should do the appropriate thing prior to passing it to this library. Hope that's ok! :)
