### ISSUE TITLE
Why you do not make pretty print

### ISSUE THREAD

**Issue by just-boris** [chilts/data2xml#16]
I am looking for a library for easy xml generating. This library the closest to my needs.
But I need pretty print for debug reasons. For example `JSON.stringify` can format its output. So, it better to have it for xml as well

**Comment by chilts** [comment]
There are other libraries that can format XML for you. This library is designed so that you can use pretty data and convert that to ugly xml at the end - mainly for consuming in other APIs, hence I'm not too worried about pretty printing. It'll just add many lines of code.

Of course, if you submitted a nice Pull Request, I'd almost certainly merge it. :)
